Repository OS-EDU/KO--CSP, pull requests merged in 2020-12, with the labels that each got.

#37 B1011题目描述
  README.md
  题目描述/B1011.md
Labels: add questions

#39 题目描述
  README.md
  csource/B1001(c).cpp
  题目描述/B1011.md
Labels: add questions

#41 增加B1011题目
  题目描述/B1011.md
Labels: add questions

#44 [Solution] 提交PAT-A1046.Shuffling Machine的解法（使用Java语言描述）
  src/introduction/simulation/A1042.java
  src/introduction/simulation/A1046.java
  题目描述/A1042.md
  题目描述/A1046.md
  题目描述/B1011.md
Labels: solution

#45 [fix wrong] 修改PAT - A1042 中的错误
  src/introduction/simulation/A1042.java
Labels: bug

#46 Java source
  src/introduction/simulation/A1042.java
  src/introduction/simulation/A1046.java
Labels: solution

#49 增加 PAT - B1010 题目描述文件
  题目描述/PAT-B1010.md
Labels: add questions

#51 [Bug] 修改 A1042.java 中的错误代码
  src/introduction/simulation/A1042.java
Labels: bug

#56 PAT-B1018C语言解法
  csource/PAT-B1018C语言解法
Labels: solution
