Repository OS-EDU/KO--CSP, pull requests merged in 2020-11, with the labels that each got.

#8 B1012解法
  src/introduction/simulation/B1012.java
Labels: solution

#11 增加B1018
  src/introduction/simulation/B1012.java
  题目描述/B1018.md
Labels: add questions

#12 题目描述
  题目描述/B1018.md
Labels: add questions

#10 B1016的c语言解法
  csource/B1016(c).cpp
  src/introduction/simulation/B1012.java
Labels: solution

#14 C source
  csource/B1016(c).cpp
Labels: solution

#15 update README.md
  README.md
Labels: documentation

#17 [invalid] 修改B1046题目描述
  csource/B1016(c).cpp
  题目描述/B1046.md
Labels: invalid

#19 B1018剪刀石头布解法[Java]
  README.md
  src/introduction/simulation/B1018.java
  题目描述/B1018.md
Labels: solution

#21 B1046的C语言解法
  csource/B1046(c).cpp
  题目描述/B1046.md
Labels: solution

#22 [Solution] B1046题目的C语言
  csource/B1046(c).cpp
Labels: solution

#26 提交B1001题目描述
  csource/B1046(c).cpp
  题目描述/B1001.md
Labels: add questions

#28 B1001的C语言解法
  csource/B1001(c).cpp
  题目描述/B1001.md
Labels: solution

#30 增加题目A1042 和 A1046 描述文件
  README.md
  src/introduction/simulation/B1018.java
  题目描述/A1042.md
  题目描述/A1046.md
Labels: add questions
