Repository OS-EDU/KO--CSP, pull requests merged in 2021-01, with the labels that each got.

#59 Update README.md
  README.md
Labels: bug

#60 [move file] 移动Java文件至指定目录
  PAT/javaSrc/B1008.java
  PAT/javaSrc/B1011.java
  PAT/javaSrc/B1012.java
  PAT/javaSrc/B1016.java
  PAT/javaSrc/B1018.java
  PAT/javaSrc/B1046.java
Labels: help wanted

#61 [move] 移动 C 文件至指定目录下
  PAT/cSrc/B1011(c).cpp
  PAT/cSrc/B1016(c).cpp
  PAT/cSrc/B1046(c).cpp
  PAT/cSrc/PAT-A1042(c).cpp
  PAT/cSrc/PAT-B1012(c).cpp
  PAT/cSrc/PAT_B1018(c).cpp
  题目描述/PAT-A1042.md
  题目描述/PAT-A1046.md
Labels: help wanted

#62 [move file] 移动 题目描述 文件至指定目录下
  PAT/题目描述/PAT-B1001.md
  PAT/题目描述/PAT-B1008.md
  PAT/题目描述/PAT-B1010.md
  PAT/题目描述/PAT-B1011.md
  PAT/题目描述/PAT-B1012.md
  PAT/题目描述/PAT-B1016.md
  PAT/题目描述/PAT-B1018.md
  PAT/题目描述/PAT-B1046.md
  题目描述/PAT-A1042.md
  题目描述/PAT-A1046.md
Labels: help wanted

#64 [Add Question]增加PAT - B1028
  PAT/题目描述/PAT-B1028.md
Labels: add questions

#66 [Add Question] 提交PAT-B1004题目描述
  PAT/题目描述/PAT-B1004.md
Labels: add questions

#68 [Add Question] 增加 PAT-B1041 题目描述文件
  PAT/题目描述/PAT-B1041.md
Labels: add questions

#72 delete java package name
  PAT/javaSrc/A1042.java
  PAT/javaSrc/B1001.java
  PAT/javaSrc/B1008.java
  PAT/javaSrc/B1011.java
  PAT/javaSrc/B1012.java
  PAT/javaSrc/B1016.java
  PAT/javaSrc/B1018.java
  PAT/javaSrc/B1046.java
Labels: documentation
